### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by Igor2024** [pykpt/smapi#1]
Добрый день! 
Попробовал код 

`from smapi import Client
client = Client(login="k*******", password="o******")
print(client.token)`

Получил ошибку 

  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/smapi/smapi.py", line 51, in __init__
    self.token = self.get_token(login, password)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/smapi/smapi.py", line 64, in get_token
    raise APIError('Неудачная авторизация')
smapi.smapi.APIError: Неудачная авторизация

Подскажите, пожалуйста, куда копать?
Также помогите, пожалуйста, разобраться, почему client_id=bafe713c96a342b194d040392cadf82b и откуда его брать для моего приложения?

**Comment by pykpt** [comment]
Авторизация не прошла либо из-за ошибки в логине и пароле либо из-за техобслуживания школьного портала. Модуль не работает во время техобслуживания, нуждается в доработке. Клиент айди нужен чисто для получения токена, указанный в модуле айди это айди случайного приложения.
